export {default} from './Batch.page.js';

/** This Export the component actions */
export const GET_BATCH = 'GET_BATCH';
export const RESET_CANDIDATE = 'RESET_CANDIDATE';
export const RESET_BATCH_UPDATE = 'RESET_BATCH_UPDATE';
export const GET_BATCH_SUCCESSFUL = 'GET_BATCH_SUCCESSFUL';
export const GET_BATCH_UNSUCCESSFUL = 'GET_BATCH_UNSUCCESSFUL';

export const REJECT_CANDIDATE_SUCCESSFUL = 'REJECT_CANDIDATE_SUCCESSFUL';
export const REJECT_CANDIDATE_UNSUCCESSFUL = 'REJECT_CANDIDATE_UNSUCCESSFUL';

export const BATCH_VERIFICATION_SUCCESSFUL = 'BATCH_VERIFICATION_SUCCESSFUL';
export const BATCH_VERIFICATION_UNSUCCESSFUL = 'BATCH_VERIFICATION_UNSUCCESSFUL';